[package]
name = "oci"
version = "0.1.0"
authors = ["Tycho Andersen <tycho@tycho.pizza>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "*"
sha2 = "*"
tee = "*"
tempfile = "*"
compression = { path = "../compression" }
format = { path = "../format" }
