[package]
name = "puzzlefs"
version = "0.1.0"
authors = ["Tycho Andersen <tycho@tycho.pizza>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
format = { path = "../format" }
builder = { path = "../builder" }
oci = { path = "../oci" }
