name: ci

on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * 0' # weekly

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
            - run: make lint check
